name: Deploy Mind to VPS

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # -----------------
      # BACKEND
      # -----------------

      - name: Set up Go 1.24
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Build Go binary
        run: |
          CGO_ENABLED=0 go build -o mind-journey-map ./cmd/server/main.go

      # -----------------
      # DEPLOY TO VPS
      # -----------------

      - name: Copy binary to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          source: "mind-journey-map"
          target: "/opt/mind-journey-map/"

      - name: Deploy systemd service
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            sudo systemctl stop mind-journey-map
            echo "KNOWLEDGE_BASE_DIR=${{ secrets.KNOWLEDGE_BASE_DIR }}" > .env
            cd /opt/mind-journey-map
            sudo systemctl start mind-journey-map
            sudo systemctl status mind-journey-map --no-pager
